### ISSUE TITLE
FAQ’s: How will new NExSS members be added? Section needs to be updated

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#16]
This can be updated as soon as the Jedi's provide the text

**Comment by jlnoviello** [comment]
Text for Affiliate Membership (no funding attachment, just wants to be in the community): NExSS is open to all members of relevant scientific communities who share our passion for interdisciplinary studies of exoplanets and astrobiology. If you are not already a NExSS member via proposal selection in a participating NASA program, you are welcome to apply for NExSS Affiliate membership. Please fill out this form and we will be in contact with you soon! 

Link: https://docs.google.com/forms/d/e/1FAIpQLSdlkWv7A_ESR1RSbH-z_FlX9zqwPDG4_v2G_CMR4Dz09vgfxQ/viewform

I'm working on the funded team membership text now, but the basic answer is the PI should fill it out and the team members should get access once the PI has agreed to join NExSS and provided the information to us. I'm working on finessing this.

**Comment by andyburnett** [comment]
@jlnoviello Sounds good. could you let me know once you have the whole document together, and then we can update the pages in one go.

**Comment by jlnoviello** [comment]
Here is the final text:

For affiliate members (those not a part of an official NExSS team): NExSS is open to all members of relevant scientific communities who share our passion for interdisciplinary studies of exoplanets and astrobiology. If you are not already a NExSS member via proposal selection in a participating NASA program, you are welcome to apply for NExSS Affiliate membership. You must read and agree to the NExSS Rules for Participation before joining NExSS ([link here](https://www.nexss.info/about/rulesfornexssparticipation)). Once you have done this, please fill out this form and we will be in contact with you soon!

Link: https://docs.google.com/forms/d/e/1FAIpQLSdlkWv7A_ESR1RSbH-z_FlX9zqwPDG4_v2G_CMR4Dz09vgfxQ/viewform

For members of NExSS teams: The Principal Investigators (PI) of successful proposals and their teams will be invited to join NExSS. NExSS will send an intake form to the PI to collect details if the PI decides that the team will join. The PI will then be responsible for submitting the names of their team members to the NExSS Management team.
