### ISSUE TITLE
Add the NExSS ICAR onboarding presentation to the website 

### ISSUE THREAD

**Issue by vsmeadows** [Knowinnovation/nexss#23]
Mary has requested that we add the NExSS overview presentation presented at the ICAR on boarding to the new website.   If we have an "about NExSS" page, it would best belong there.  The presentation is attached below. 
[NExSS_ICAR_onboarding_final2.pptx](https://github.com/Knowinnovation/nexss/files/6167797/NExSS_ICAR_onboarding_final2.pptx)

**Comment by andyburnett** [comment]
@adnanjamil-frontend I think it would be best to add the file to the media library and put a hyperlink on the about us page.

**Comment by adnanjamil-frontend** [comment]
Added at the end of the first paragraph.
