### ISSUE TITLE
Give Jessica, Miles Currie, and Pilar Vergeli editing access to the "blog" style part of the website

### ISSUE THREAD

**Issue by jlnoviello** [Knowinnovation/nexss#24]
Miles' email: mcurr@uw.edu
Pilar's email: pvergeli@asu.edu 

We'll start doing the website as a .pdf and as a blog-style posting platform in May!

**Comment by andyburnett** [comment]
All three of you should now have received invitations to the site. Let's arrange a time to walk through the authoring and editing process.
