### ISSUE TITLE
Give Alan Jackson editing access to the Wordpress site

### ISSUE THREAD

**Issue by jlnoviello** [Knowinnovation/nexss#25]
I know we talked about doing this, but I was talking to Alan yesterday and we are both unsure if he ever got an invite to be an editor on the NExSS site. He'll be at the website meeting on 4/30.

**Comment by andyburnett** [comment]
This is very strange. I have an email chain where Alan is acknowledging receipt of the invite, but I also don't see him in the invite list. Perhaps I got confused about which site he was being invited to. Anyway, I have gone through the invite process again, and hopefully Alan will have an invite now.
