### ISSUE TITLE
Make naming of newsletters consistent

### ISSUE THREAD

**Issue by ajacksonastro** [Knowinnovation/nexss#26]
The newsletters for February, March and April 2021 are named "Newsletter for X 2021", January is named as "NExSS Newsletter for January 2021" and the ones before that are named "August/September/October/December Newsletter" without a year.  The names should be made consistent (and should include the year as well as the month).

**Comment by ajacksonastro** [comment]
I've updated the names so that they are all now in the form "[Month] [Year] NExSS Newsletter"

**Comment by andyburnett** [comment]
Great! I will mark this as closed.
