### ISSUE TITLE
Add Habitable Worlds Conference page with text from Jessica

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#3]

**Comment by andyburnett** [comment]
Awaiting text from Jessica

**Comment by jlnoviello** [comment]
Working on it!

**Comment by jlnoviello** [comment]
As this meeting has passed I don't think we need this text anymore. The only thing I could think of is we could make a sample blog post with the story that Miles had in the March Newsletter

**Comment by andyburnett** [comment]
I think a blog post sounds good. I will leave this with you, and mark the issue as closed now
