### ISSUE TITLE
Add white papers

### ISSUE THREAD

**Issue by ajacksonastro** [Knowinnovation/nexss#31]
To Community -> NExSS Publications -> White papers add the articles listed under http://www.nexss.info/workshopreports

Also, change "Community Resources" to "TRAPPIST-1 JWST Community Initiative" and link directly to the TRAPPIST-1 JWST white paper on ArXiv rather than linking to Community Resources under TRAPPIST-1.

**Comment by jlnoviello** [comment]
I am working on this now
