### ISSUE TITLE
Landing Page: Top-panel sliders: use NExSS-related images, team photo, rather than stock images

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#5]
We need to get images from Jessica

**Comment by jlnoviello** [comment]
Having not had an in-person conference in over a year with NExSS people present, pictures are hard to come by. This is the default one I use. Photo credit to the LPI staff
![EioB_2020](https://user-images.githubusercontent.com/13666168/111179346-5ef09580-8582-11eb-86dc-5b11321e3f06.png)
