### ISSUE TITLE
Landing Page: Top-panel sliders: add NExSS YouTube channel

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#6]
Ideally, we need a square graphic for the channel

**Comment by jlnoviello** [comment]
![NExSS_SocialMedia](https://user-images.githubusercontent.com/13666168/111170935-d7535880-857a-11eb-8128-0dfcb37bef10.png)

**Comment by jlnoviello** [comment]
This will have to be updated if we ever get another social media profile
