### ISSUE TITLE
Landing Page: New Module: NExSS Newsletters

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#7]
We need a square graphic for the newsletter module

**Comment by jlnoviello** [comment]
![NExSS_Newsletter](https://user-images.githubusercontent.com/13666168/111170759-ad019b00-857a-11eb-930c-3c87c944d90f.png)

**Comment by jlnoviello** [comment]
Is there a way I can mark this task as "done?"

**Comment by andyburnett** [comment]
You might have the ability to click the 'close with comment' button. However, I am actually going to reassign this to Adnan now, so that he can add it to the site.
