### ISSUE TITLE
Landing Page: Current Nugget ---> Science Nuggets

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#9]
I think the request is to change Current Nugget to say Science Nuggets

**Comment by andyburnett** [comment]
@jlnoviello Can you clarify what this means. Initially I thought it was a request to rename the menu item, but the menu item does say Science Nuggets, so now we are confused.

**Comment by jlnoviello** [comment]
I think this is meant to refer to the text on the carousel. I've made a square graphic for the science nuggets to use there, and I guess clicking on it should take the user to the latest science nugget. We'll need to check this with the Leads and Alan.
![NExSS_ScienceNuggets](https://user-images.githubusercontent.com/13666168/111171665-8132e500-857b-11eb-8395-5561592155c9.png)

**Comment by andyburnett** [comment]
sounds good. Let's implement it for now, and see what people have to say
